seed: 0
exp_name: 0th_trial_40000_data
batch_size: 4
eval_batch_size: 2
debug: false
fsdp_port: null
datasets:
- custom
wandb:
  enabled: true
  entity: null
  project: direct-preference-optimization
local_dirs:
- /scr-ssd
- /scr
- .cache
sample_during_eval: false
n_eval_model_samples: 16
do_first_eval: true
local_run_dir: ./config
lr: 5.0e-07
gradient_accumulation_steps: 2
max_grad_norm: 10.0
max_length: 512
max_prompt_length: 256
n_epochs: 1
n_examples: null
n_eval_examples: 256
trainer: BasicTrainer
optimizer: RMSprop
warmup_steps: 150
activation_checkpointing: false
eval_every: 348
minimum_log_interval_secs: 1.0
model:
  name_or_path: PrunaAI/saltlux-Ko-Llama3-Luxia-8B-bnb-4bit-smashed
  tokenizer_name_or_path: PrunaAI/saltlux-Ko-Llama3-Luxia-8B-bnb-4bit-smashed
  archive: null
  block_name: null
  policy_dtype: float32
  fsdp_policy_mp: null
  reference_dtype: float16
loss:
  name: sft
  beta: 2
  label_smoothing: 1
  reference_free: false
